/*************************************************************************
 * reech4x4.h -
 *
 * $Id: reech4x4.begin,v 1.3 2001/12/10 08:45:17 greg Exp $
 *
 * Copyright (c) INRIA 1999
 *
 * AUTHOR:
 * Gregoire Malandain (greg@sophia.inria.fr)
 * 
 * CREATION DATE: 
 *
 *
 * ADDITIONS, CHANGES
 *	
 *	
 *	
 *
 */


/* CAUTION
   DO NOT EDIT THIS FILE,
   UNLESS YOU HAVE A VERY GOOD REASON 
 */

#ifndef _cspline4x4_h_
#define _cspline4x4_h_

#ifdef __cplusplus
extern "C" {
#endif

#include <cspline-coeff.h>

extern void setVerboseInCspline4x4( int v );
extern void incrementVerboseInCspline4x4(  );
extern void decrementVerboseInCspline4x4(  );



extern int Cspline3D4x4_u8 ( typeCSplineCoefficients *theCoeff,
                                void* resBuf, /* result buffer */
                                int *resDim,  /* dimensions of this buffer */
                                double* mat,   /* transformation matrix */
                                int *derivative
                              );




extern int Cspline3D4x4_s8 ( typeCSplineCoefficients *theCoeff,
                                void* resBuf, /* result buffer */
                                int *resDim,  /* dimensions of this buffer */
                                double* mat,   /* transformation matrix */
                                int *derivative
                              );




extern int Cspline3D4x4_u16 ( typeCSplineCoefficients *theCoeff,
                                void* resBuf, /* result buffer */
                                int *resDim,  /* dimensions of this buffer */
                                double* mat,   /* transformation matrix */
                                int *derivative
                              );




extern int Cspline3D4x4_s16 ( typeCSplineCoefficients *theCoeff,
                                void* resBuf, /* result buffer */
                                int *resDim,  /* dimensions of this buffer */
                                double* mat,   /* transformation matrix */
                                int *derivative
                              );




extern int Cspline3D4x4_r32 ( typeCSplineCoefficients *theCoeff,
                                void* resBuf, /* result buffer */
                                int *resDim,  /* dimensions of this buffer */
                                double* mat,   /* transformation matrix */
                                int *derivative
                              );




#ifdef __cplusplus
}
#endif

#endif
