#
# files
#
OUTPUT_TEMP = "../"

# templates pour le reechantillonnage
include GNUmakefile.reech

# templates pour la morphologie mathematique
include GNUmakefile.morpho

rmtmp : 
	rm -f ${REECH_FILES} ${MORPHO_FILES}


