/*************************************************************************
 * reech4x4.h -
 *
 * $Id: reech4x4.begin,v 1.3 2001/12/10 08:45:17 greg Exp $
 *
 * Copyright (c) INRIA 1999
 *
 * AUTHOR:
 * Gregoire Malandain (greg@sophia.inria.fr)
 * 
 * CREATION DATE: 
 *
 *
 * ADDITIONS, CHANGES
 *	
 *	
 *	
 *
 */


/* CAUTION
   DO NOT EDIT THIS FILE,
   UNLESS YOU HAVE A VERY GOOD REASON 
 */

#ifndef _cspline4x4_h_
#define _cspline4x4_h_

#ifdef __cplusplus
extern "C" {
#endif

#include <cspline-coeff.h>

extern void setVerboseInCspline4x4( int v );
extern void incrementVerboseInCspline4x4(  );
extern void decrementVerboseInCspline4x4(  );
