/*************************************************************************
 * reech-def.h -
 *
 * $Id: reech-def.begin,v 1.2 2000/10/18 08:45:56 greg Exp $
 *
 * Copyright (c) INRIA 1999
 *
 * AUTHOR:
 * Gregoire Malandain (greg@sophia.inria.fr)
 * 
 * CREATION DATE: 
 *
 *
 * ADDITIONS, CHANGES
 *	
 *	
 *	
 *
 */


/* CAUTION
   DO NOT EDIT THIS FILE,
   UNLESS YOU HAVE A VERY GOOD REASON 
 */

#ifndef _reech_def_h_
#define _reech_def_h_

#ifdef __cplusplus
extern "C" {
#endif

#include <typedefs.h>



extern void setVerboseInReechDef( int v );
extern void incrementVerboseInReechDef(  );
extern void decrementVerboseInReechDef(  );
